const $=s=>document.querySelector(s);
const escapeHtml=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const fmt=n=>Number(n).toLocaleString('en-US');
const fieldMap={climate:'climate',country:'country',continent:'continent',family:'family',design:'design',pattern:'pattern'};
const inputs={climate:$('#climate'),country:$('#country'),continent:$('#continent'),family:$('#family'),design:$('#design'),pattern:$('#pattern'),search:$('#search')};
const canvas=$('#plot'),ctx=canvas.getContext('2d'),tooltip=$('#tooltip');canvas.tabIndex=0;
let countryPolygons=[],indiaPolygons=[],indiaOutlineLines=[],data=[],columns=[],filtered=[],articles=[],plotted=[],selectedArticle=null,selected=null,lastClick={x:-100,y:-100,index:0},view={scale:1,x:0,y:0},drag=null,suppressClick=false;
const pad={left:48,right:22,top:23,bottom:37};
const transform=(x,y)=>({x:canvas.width/2+(x-canvas.width/2)*view.scale+view.x,y:canvas.height/2+(y-canvas.height/2)*view.scale+view.y});
const coord=r=>transform(pad.left+(Number(r.longitude)+180)/360*(canvas.width-pad.left-pad.right),pad.top+(90-Number(r.latitude))/180*(canvas.height-pad.top-pad.bottom));
const hasCoords=r=>r.latitude!=null&&r.longitude!=null&&Number.isFinite(Number(r.latitude))&&Number.isFinite(Number(r.longitude))&&Math.abs(Number(r.latitude))<=90&&Math.abs(Number(r.longitude))<=180;
const radius=a=>Math.max(3,Math.sqrt(a.count/Math.PI)*1.75);
const groupValue=(r,key)=>key==='designPattern'?`${String(r.design??'Unspecified').trim()||'Unspecified'} · ${String(r.pattern??'Unspecified').trim()||'Unspecified'}`:String(r[key]??'Unspecified').trim()||'Unspecified';
const matchesGroup=(r,key,value)=>!value||(value==='__UNSPECIFIED__'?groupValue(r,key)==='Unspecified':r[key]===value);
function fill(el,values){for(const v of [...new Set(values.filter(Boolean))].sort((a,b)=>String(a).localeCompare(String(b)))){const o=document.createElement('option');o.value=v;o.textContent=v;el.append(o)}const unknown=document.createElement('option');unknown.value='__UNSPECIFIED__';unknown.textContent='Unspecified';el.append(unknown)}
function aggregate(rows){const map=new Map();for(const r of rows){if(r.article==null)continue;const key=String(r.article);if(!map.has(key))map.set(key,{id:r.article,title:r.title,country:r.country,climate:r.climate,year:r.year,latitude:null,longitude:null,count:0,rows:[]});const a=map.get(key);a.count++;a.rows.push(r);if(a.latitude==null&&hasCoords(r)){a.latitude=r.latitude;a.longitude=r.longitude}}return [...map.values()]}
function apply(){const q=inputs.search.value.trim().toLowerCase();filtered=data.filter(r=>Object.entries(fieldMap).every(([key,col])=>matchesGroup(r,col,inputs[key].value))&&(!q||[r.title,r.authors,r.crop1,r.crop2,r.insect,r.doi].some(x=>String(x??'').toLowerCase().includes(q))));articles=aggregate(filtered);plotted=articles.filter(hasCoords);$('#plot-status').textContent=`${fmt(plotted.length)} located articles`;$('#filter-status').textContent=`${fmt(filtered.length)} matching observations · ${fmt(articles.length)} articles`;selectedArticle=articles.find(a=>a.id===selectedArticle?.id)||articles[0]||null;if(!selectedArticle||!selectedArticle.rows.includes(selected))selected=selectedArticle?.rows[0]||null;draw();showDetail();drawGroups()}
function drawPolygons(polygons,fill,stroke,width=1){ctx.fillStyle=fill;ctx.strokeStyle=stroke;ctx.lineWidth=Math.max(.55,width/view.scale);for(const polygon of polygons){ctx.beginPath();for(const ring of polygon){ring.forEach(([lon,lat],i)=>{const p=coord({longitude:lon,latitude:lat});if(i)ctx.lineTo(p.x,p.y);else ctx.moveTo(p.x,p.y)});ctx.closePath()}ctx.fill('evenodd');if(width)ctx.stroke()}}
function drawLines(lines,stroke,width=1){ctx.strokeStyle=stroke;ctx.lineWidth=Math.max(.55,width/view.scale);for(const line of lines){ctx.beginPath();line.forEach(([lon,lat],i)=>{const p=coord({longitude:lon,latitude:lat});if(i)ctx.lineTo(p.x,p.y);else ctx.moveTo(p.x,p.y)});ctx.stroke()}}
function topoOutline(topology){const usage=new Map(),visit=arcs=>{if(typeof arcs==='number'){const i=arcs<0?-arcs-1:arcs;usage.set(i,(usage.get(i)||0)+1)}else arcs.forEach(visit)};topology.objects.data.geometries.forEach(g=>visit(g.arcs));const [sx,sy]=topology.transform.scale,[tx,ty]=topology.transform.translate;return topology.arcs.map((arc,i)=>{let x=0,y=0;return arc.map(([dx,dy])=>{x+=dx;y+=dy;return [tx+x*sx,ty+y*sy]})}).filter((_,i)=>usage.get(i)===1)}
function drawCountries(){drawPolygons(countryPolygons,'#edf3f0','#a9beb8');drawPolygons(indiaPolygons,'#edf3f0','#a9beb8',0);drawLines(indiaOutlineLines,'#a9beb8')}
function draw(){const w=canvas.width,h=canvas.height;ctx.clearRect(0,0,w,h);ctx.fillStyle='#f8fbfa';ctx.fillRect(0,0,w,h);drawCountries();ctx.strokeStyle='#dde9e5';ctx.lineWidth=1;ctx.font='12px system-ui';ctx.fillStyle='#6d8383';for(let lon=-180;lon<=180;lon+=60){const base=pad.left+(lon+180)/360*(w-pad.left-pad.right),top=transform(base,pad.top),bottom=transform(base,h-pad.bottom);ctx.beginPath();ctx.moveTo(top.x,top.y);ctx.lineTo(bottom.x,bottom.y);ctx.stroke();if(bottom.x>=0&&bottom.x<=w)ctx.fillText(`${lon}°`,bottom.x-14,Math.min(h-8,bottom.y+22))}for(let lat=-60;lat<=60;lat+=30){const base=pad.top+(90-lat)/180*(h-pad.top-pad.bottom),left=transform(pad.left,base),right=transform(w-pad.right,base);ctx.beginPath();ctx.moveTo(left.x,left.y);ctx.lineTo(right.x,right.y);ctx.stroke();if(left.y>=0&&left.y<=h)ctx.fillText(`${lat}°`,Math.max(5,left.x-40),left.y+4)}ctx.strokeStyle='#9cb8b1';const tl=transform(pad.left,pad.top),br=transform(w-pad.right,h-pad.bottom);ctx.strokeRect(tl.x,tl.y,br.x-tl.x,br.y-tl.y);for(const a of [...plotted].sort((a,b)=>b.count-a.count)){const {x,y}=coord(a);ctx.beginPath();ctx.arc(x,y,radius(a)*Math.min(view.scale,1.8),0,Math.PI*2);ctx.fillStyle=a.climate?.startsWith('A')?'#dc7657':a.climate?.startsWith('C')?'#3e9790':'#849497';ctx.globalAlpha=.8;ctx.fill();ctx.globalAlpha=1;ctx.strokeStyle='#fff';ctx.lineWidth=1.6;ctx.stroke()}if(selectedArticle&&hasCoords(selectedArticle)){const {x,y}=coord(selectedArticle);ctx.beginPath();ctx.arc(x,y,radius(selectedArticle)*Math.min(view.scale,1.8)+3,0,Math.PI*2);ctx.strokeStyle='#203a3d';ctx.lineWidth=3;ctx.stroke()}}
function showDetail(){if(!selected){$('#detail-heading').textContent='No matching article';$('#detail-subtitle').textContent='Change the filters to see articles.';$('#detail-highlights').replaceChildren();$('#detail-fields').replaceChildren();$('#detail-doi').hidden=true;$('#download-article').disabled=true;$('#view-selected').disabled=true;$('#selected-count').textContent='';$('#record-position').textContent='0 of 0';$('#prev-record').disabled=true;$('#next-record').disabled=true;return}const r=selected,a=selectedArticle,position=a.rows.indexOf(r);$('#detail-heading').textContent=a.title||'Untitled article';$('#detail-subtitle').textContent=`${fmt(a.count)} observations · ${a.country||'Country unknown'} · ${a.year||'Year unknown'}`;$('#selected-count').textContent=`Article ${a.id}`;$('#record-position').textContent=`Observation ${fmt(position+1)} of ${fmt(a.count)}`;$('#prev-record').disabled=position<=0;$('#next-record').disabled=position>=a.count-1;$('#download-article').disabled=false;$('#view-selected').disabled=false;const chips=[['Insect',r.insect],['Family',r.family],['Role',r.role],['Crop pairing',[r.crop1,r.crop2].filter(Boolean).join(' + ')],['Climate',r.climate],['Count definition',r.countType],['Crop 1 abundance',r.crop1Value],['Crop 2 abundance',r.crop2Value],['Intercropped abundance',r.intercropValue]];$('#detail-highlights').innerHTML='<div class="highlights">'+chips.map(([k,v])=>`<div><small>${escapeHtml(k)}</small><strong>${escapeHtml(v??'Not recorded')}</strong></div>`).join('')+'</div>';const design=[r.raw.Intercropping_design,r.raw.Intercropping_pattern].filter(Boolean).join(' · ');$('#detail-highlights').insertAdjacentHTML('afterbegin',`<p class="design-line"><strong>Intercropping:</strong> ${escapeHtml([r.crop1,r.crop2].filter(Boolean).join(' + ')||'Not recorded')} · ${escapeHtml(design||'Design not recorded')}<br><strong>Insect:</strong> ${escapeHtml(r.insect||'Not recorded')} · ${escapeHtml([r.role,r.raw.Insect_role_type].filter(Boolean).join(' / ')||'Role not recorded')}</p>`);drawAbundance(r);$('#detail-fields').innerHTML=columns.map(c=>`<div><dt>${escapeHtml(c)}</dt><dd>${escapeHtml(r.raw[c]??'Not recorded')}</dd></div>`).join('');const link=$('#detail-doi');if(/^https:\/\/doi\.org\//i.test(r.doi||'')){link.href=r.doi;link.hidden=false}else link.hidden=true}
function drawAbundance(r){const root=$('#abundance-chart');root.replaceChildren();const title=document.createElement('h4');title.textContent='Insect abundance in this observation';root.append(title);const measure=document.createElement('p');measure.textContent=r.countType?`Reported measure: ${r.countType}`:'Measurement definition not recorded';root.append(measure);const values=[['Monocrop · '+(r.crop1||'crop 1'),r.crop1Value],['Monocrop · '+(r.crop2||'crop 2'),r.crop2Value],['Intercrop',r.intercropValue]];const nums=values.map(([,v])=>v===null||v===undefined||String(v).trim()===''?null:Number(String(v).replace(/,/g,'')));const max=Math.max(0,...nums.filter(Number.isFinite));values.forEach(([label,value],i)=>{const line=document.createElement('div');line.className='abundance-row';const name=document.createElement('span');name.textContent=label;const track=document.createElement('div');track.className='abundance-track';const bar=document.createElement('i');const n=nums[i];bar.style.width=Number.isFinite(n)&&n>=0&&max>0?`${n/max*100}%`:'0%';if(i===2)bar.classList.add('intercrop-bar');track.append(bar);const amount=document.createElement('strong');amount.textContent=Number.isFinite(n)?String(value):value==null||String(value).trim()===''?'Not reported':String(value);line.append(name,track,amount);root.append(line)});const caveat=document.createElement('small');caveat.textContent='Values are shown as reported for this record; bars use the largest nonnegative value as their scale. Missing values are not zero.';root.append(caveat)}
function articleAt(evt){const box=canvas.getBoundingClientRect(),x=(evt.clientX-box.left)*canvas.width/box.width,y=(evt.clientY-box.top)*canvas.height/box.height;const matches=[];for(const a of plotted){const p=coord(a),d=Math.hypot(p.x-x,p.y-y);if(d<=radius(a)*Math.min(view.scale,1.8)+5)matches.push({article:a,distance:d})}matches.sort((a,b)=>a.distance-b.distance);return {matches,x:evt.clientX-box.left,y:evt.clientY-box.top}}
canvas.addEventListener('mousemove',e=>{const hit=articleAt(e);if(!hit.matches.length){tooltip.hidden=true;return}const a=hit.matches[0]?.article;if(!a){tooltip.hidden=true;return}tooltip.hidden=false;tooltip.textContent=`Article ${a.id} · ${fmt(a.count)} observations · ${a.country||'Unknown country'} ${hit.matches.length>1?' · click again for overlapping articles':''}`;tooltip.style.left=Math.min(hit.x+12,canvas.getBoundingClientRect().width-260)+'px';tooltip.style.top=Math.max(6,hit.y-55)+'px'});canvas.addEventListener('mouseleave',()=>tooltip.hidden=true);canvas.addEventListener('click',e=>{if(suppressClick){suppressClick=false;return}const hit=articleAt(e);if(!hit.matches.length)return;const repeat=Math.hypot(hit.x-lastClick.x,hit.y-lastClick.y)<8;lastClick.index=repeat?(lastClick.index+1)%hit.matches.length:0;lastClick.x=hit.x;lastClick.y=hit.y;selectedArticle=hit.matches[lastClick.index].article;selected=selectedArticle.rows[0];draw();showDetail();openDetail()});canvas.addEventListener('keydown',e=>{if(!plotted.length)return;const i=plotted.findIndex(a=>a.id===selectedArticle?.id);if(e.key==='ArrowRight'||e.key==='ArrowDown'){e.preventDefault();selectedArticle=plotted[(i+1)%plotted.length]}else if(e.key==='ArrowLeft'||e.key==='ArrowUp'){e.preventDefault();selectedArticle=plotted[(i-1+plotted.length)%plotted.length]}else return;selected=selectedArticle.rows[0];draw();showDetail()});

function zoomAt(factor,x=canvas.width/2,y=canvas.height/2){const old=view.scale,next=Math.max(1,Math.min(8,old*factor));view.x=(x-canvas.width/2)-(x-canvas.width/2-view.x)*next/old;view.y=(y-canvas.height/2)-(y-canvas.height/2-view.y)*next/old;view.scale=next;if(next===1){view.x=0;view.y=0}draw()}
$('#zoom-in').onclick=()=>zoomAt(1.45);$('#zoom-out').onclick=()=>zoomAt(1/1.45);$('#zoom-reset').onclick=()=>{view={scale:1,x:0,y:0};draw()};
canvas.addEventListener('wheel',e=>{e.preventDefault();const b=canvas.getBoundingClientRect();zoomAt(e.deltaY<0?1.23:1/1.23,(e.clientX-b.left)*canvas.width/b.width,(e.clientY-b.top)*canvas.height/b.height)},{passive:false});
canvas.addEventListener('pointerdown',e=>{drag={x:e.clientX,y:e.clientY,moved:false};canvas.setPointerCapture(e.pointerId);canvas.classList.add('dragging')});
canvas.addEventListener('pointermove',e=>{if(!drag)return;const box=canvas.getBoundingClientRect(),dx=(e.clientX-drag.x)*canvas.width/box.width,dy=(e.clientY-drag.y)*canvas.height/box.height;if(Math.abs(dx)+Math.abs(dy)>0){view.x+=dx;view.y+=dy;drag.x=e.clientX;drag.y=e.clientY;drag.moved=true;tooltip.hidden=true;draw()}});
canvas.addEventListener('pointerup',()=>{if(drag?.moved)suppressClick=true;drag=null;canvas.classList.remove('dragging')});
canvas.addEventListener('pointercancel',()=>{drag=null;canvas.classList.remove('dragging')});
function openDetail(){if(!selectedArticle)return;$('#detail-backdrop').hidden=false;const card=$('.detail-card');card.classList.add('open');card.setAttribute('aria-hidden','false');$('#close-detail').focus()}
function closeDetail(){const card=$('.detail-card');card.classList.remove('open');card.setAttribute('aria-hidden','true');$('#detail-backdrop').hidden=true;$('#view-selected').focus()}
$('#view-selected').onclick=openDetail;$('#close-detail').onclick=closeDetail;$('#detail-backdrop').onclick=closeDetail;document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('.detail-card').classList.contains('open'))closeDetail()});

function csv(rows){const quote=v=>{if(v==null)return '';let s=String(v);if(/^[=+@\-\t\r]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"'};return '\ufeff'+[columns.map(quote).join(','),...rows.map(r=>columns.map(c=>quote(r.raw[c])).join(','))].join('\r\n')}
function download(rows,name){if(!rows.length)return;const blob=new Blob([csv(rows)],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),5000)}
function slug(s){return String(s).normalize('NFKD').replace(/[^a-zA-Z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,65)||'unspecified'}
function drawGroups(){const key=$('#group-by').value,groups=new Map();for(const r of filtered){const val=groupValue(r,key);if(!groups.has(val))groups.set(val,[]);groups.get(val).push(r)}const sorted=[...groups].sort((a,b)=>b[1].length-a[1].length||a[0].localeCompare(b[0]));const target=$('#group-list');target.replaceChildren();for(const [value,rows] of sorted){const card=document.createElement('article');card.className='group-card';const title=document.createElement('h3');title.textContent=value;const desc=document.createElement('p');desc.textContent=`${fmt(rows.length)} observations · ${fmt(new Set(rows.map(r=>r.article).filter(x=>x!=null)).size)} articles`;const actions=document.createElement('div');actions.className='group-actions';const view=document.createElement('button');view.type='button';view.textContent='View articles';view.onclick=()=>{if(key==='designPattern'){const [design,pattern]=value.split(' · ');inputs.design.value=design==='Unspecified'?'__UNSPECIFIED__':design;inputs.pattern.value=pattern==='Unspecified'?'__UNSPECIFIED__':pattern}else inputs[key].value=value==='Unspecified'?'__UNSPECIFIED__':value;apply();$('#explore').scrollIntoView({behavior:'smooth'})};const dl=document.createElement('button');dl.type='button';dl.className='primary';dl.textContent='Download CSV';dl.setAttribute('aria-label',`Download ${value} records as CSV`);dl.onclick=()=>download(rows,`intercropping_${key}_${slug(value)}.csv`);actions.append(view,dl);card.append(title,desc,actions);target.append(card)}if(!sorted.length)target.textContent='No groups match the current filters.'}
$('#prev-record').onclick=()=>{const i=selectedArticle?.rows.indexOf(selected)??-1;if(i>0){selected=selectedArticle.rows[i-1];showDetail()}};$('#next-record').onclick=()=>{const i=selectedArticle?.rows.indexOf(selected)??-1;if(selectedArticle&&i<selectedArticle.rows.length-1){selected=selectedArticle.rows[i+1];showDetail()}};$('#download-article').onclick=()=>selectedArticle&&download(selectedArticle.rows,`intercropping_article_${selectedArticle.id}.csv`);
for(const el of Object.values(inputs))el.addEventListener(el===inputs.search?'input':'change',apply);$('#clear').onclick=()=>{for(const el of Object.values(inputs))el.value='';apply()};$('#group-by').onchange=drawGroups;$('#download-filtered').onclick=()=>download(filtered,'intercropping_matching_records.csv');
fetch('data/observations.json').then(r=>{if(!r.ok)throw Error('Data unavailable');return r.json()}).then(obj=>{data=obj.records;columns=obj.columns;fill(inputs.climate,data.map(r=>r.climate));fill(inputs.country,data.map(r=>r.country));fill(inputs.continent,data.map(r=>r.continent));fill(inputs.family,data.map(r=>r.family));fill(inputs.design,data.map(r=>r.design));fill(inputs.pattern,data.map(r=>r.pattern));apply()}).catch(()=>{$('#plot-status').textContent='Data could not be loaded';$('#filter-status').textContent='Please refresh the page.'});

fetch('https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_110m_admin_0_countries.geojson').then(r=>{if(!r.ok)throw Error('Map boundaries unavailable');return r.json()}).then(geo=>{countryPolygons=geo.features.filter(f=>![f.properties?.ADM0_A3,f.properties?.SOV_A3,f.properties?.ADMIN].includes('IND')&&f.properties?.ADMIN!=='India').flatMap(f=>f.geometry?.type==='Polygon'?[f.geometry.coordinates]:f.geometry?.type==='MultiPolygon'?f.geometry.coordinates:[]);draw()}).catch(()=>{const note=document.createElement('span');note.className='boundary-note';note.textContent='Country outlines could not load';$('.plot-axis').append(note)});
fetch('data/india-boundaries.geojson').then(r=>{if(!r.ok)throw Error('India boundary unavailable');return r.json()}).then(geo=>{indiaPolygons=geo.features.flatMap(f=>f.geometry?.type==='Polygon'?[f.geometry.coordinates]:f.geometry?.type==='MultiPolygon'?f.geometry.coordinates:[]);draw()}).catch(()=>{const note=document.createElement('span');note.className='boundary-note';note.textContent='India boundary could not load';$('.plot-axis').append(note)});
fetch('data/india-boundary-topology.json').then(r=>{if(!r.ok)throw Error('India outline unavailable');return r.json()}).then(topo=>{indiaOutlineLines=topoOutline(topo);draw()}).catch(()=>{const note=document.createElement('span');note.className='boundary-note';note.textContent='India outline could not load';$('.plot-axis').append(note)});
const contribution=$('#contribution-form');contribution.addEventListener('submit',event=>{event.preventDefault();if(!contribution.reportValidity())return;const details=[...new FormData(contribution)].map(([key,value])=>`${key.replace(/([A-Z])/g,' $1').replace(/^./,c=>c.toUpperCase())}: ${String(value).trim()||'Not provided'}`).join('\n');const subject='Intercropping observation contribution for review';const body=`Hello Adrija,\n\nPlease review this proposed observation.\n\n${details}\n\nThank you.`;$('#contribution-status').textContent='Your email application should open. Please send the message there to complete your submission.';window.location.href=`mailto:dattaadrija@iitgn.ac.in?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`});

$('#comment-form').addEventListener('submit',event=>{event.preventDefault();const form=event.currentTarget;if(!form.reportValidity())return;const info=new FormData(form);const subject='Intercropping Evidence Atlas: question or comment';const body=`From: ${info.get('email')}\n\n${info.get('comment')}`;$('#comment-status').textContent='Your email application should open. Press Send there to share your comment.';window.location.href=`mailto:dattaadrija@iitgn.ac.in?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`});
